db.server = SRVQPRIV\\SQLEXPRESS
db.database = SiriusQuality
db.user = SSMAdmin
db.password = 12345678
db.port = 1433
db.token = b6d77081557ad511f40752004839a8aa
db.timeIntervalInMinutes = 15
db.deactivateUserIntervalInHrs = 24
db.emailhost = 192.168.10.3
db.emailport = 25
apiUrl = https://damico.staging.maritimetrainer.com/webservice/restful/server.php/